spring:
  datasource:
    username: mgmgzues
    password: hello
    url: jdbc:mysql://localhost:3306/file_handling
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

project:
  poster: posters/

base:
  url: "http://localhost:8080"